### ISSUE TITLE
A small bug.

### ISSUE THREAD

**Issue by ghost** [mspaintmsi/superUser#8]
![image](https://user-images.githubusercontent.com/37485357/141696433-1d7f5a4c-5b70-4242-8191-ddde85962e6a.png)
![image](https://user-images.githubusercontent.com/37485357/141696464-8829d590-97ad-42d6-8256-ae0c3f93c455.png)

**Comment by Michaelj-maker** [comment]
How's the issue?

**Comment by Matrix3600** [comment]
This issue is fixed by #9.
